# Generated by Django 4.0.3 on 2022-05-12 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_user_userphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceramah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('Deskripsi', models.CharField(max_length=800)),
                ('Waktu', models.DateField()),
                ('Link', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserID',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2022, 5, 12, 2, 11, 35, 782605, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='UserPhone',
            field=models.IntegerField(null=True),
        ),
    ]
