# Generated by Django 4.0.3 on 2022-05-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_user_id_ceramah_images_ceramah_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceramah',
            name='Images',
            field=models.ImageField(max_length=250, upload_to=''),
        ),
    ]
