# Generated by Django 4.0.3 on 2022-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_ceramah_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceramah',
            name='Link',
            field=models.URLField(max_length=100),
        ),
    ]
