# Generated by Django 4.0.3 on 2022-05-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_ceramah_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceramah',
            name='Link',
            field=models.URLField(),
        ),
    ]
